sudo: required
language: minimal

services:
  - docker

before_install:
  - docker build -t tcprescott/tileroombot .
  - docker tag tileroombot tcprescott/tileroombot:latest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
