sudo: required
language: minimal

services:
  - docker

before_install:
  - docker build -t tcprescott/tileroombot .

deploy:
  provider: script
  script: bash -x docker_push.sh
  on:
    branch: master
