version: '3.1'

services:
  tileroombot:
    container_name: 'tileroombot'
    image: tcprescott/tileroombot:latest
    volumes:
     - ./cfg/config.ini:/usr/src/app/cfg/config.ini
     - ./logs/:/usr/src/app/logs/
     - ./data/:/usr/src/app/data/
    restart: always
networks:
  docker-network:
    driver: bridge
